spring:
  application:
    name: chatbotq

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  error:
    include-message: never
    include-stacktrace: never
